### ISSUE TITLE
请问客户端能不能在windows的C#程序上使用

### ISSUE THREAD

**Issue by ghost** [fdslight/fdslight#1]
请问客户端能不能在windows的C#程序上使用

**Comment by fdslight** [comment]
抱歉，并不支持windows，开发之初就是打算放在路由上面的，而且路由自身也无法走代理。只能是哪些设置了流量走该路由的机器。并且部署了软件的本地机器走代理也有很多限制，所以默认客户端并未包含，本来想开发个windows版本，但是我不会写windows驱动😦
