### ISSUE TITLE
when I deploy over depend on your wiki ,the below error occours

### ISSUE THREAD

**Issue by comk88** [fdslight/fdslight#4]
when I deploy over depend on your wiki ,the below error occours,is any thing I was wrong?  3Q

ubuntu@ip-10-230-10-252:/export/fdslight$ /opt/bin/python3.5 fdsl_client.py -m gateway -d debug
Traceback (most recent call last):
  File "fdsl_client.py", line 705, in <module>
    if __name__ == '__main__': main()
  File "fdsl_client.py", line 699, in main
    __start_service(m, debug, only_http_socks5, no_http_socks5)
  File "fdsl_client.py", line 618, in __start_service
    cls.ioloop(mode, debug, configs, only_http_socks5, no_http_socks5)
  File "/export/fdslight/pywind/evtframework/evt_dispatcher.py", line 81, in ioloop
    self.init_func(*args, **kwargs)
  File "fdsl_client.py", line 174, in init_func
    app_proxy_configs = configs["app_proxy"]
KeyError: 'app_proxy'

and when I modify the config file like bellow:
[app_proxy]
listen_ip=127.0.0.1
listen_port=9000
the error disappear, but I still cant connect to the server ,anything else I need to modify ? or something else I need to do ? 3Q

**Comment by fdslight** [comment]
Do you clone the lastest code?and it is unstable for http and socks5 proxy

**Comment by fdslight** [comment]
if you run on server, you should use 'fdsl_server.py -d debug' as root, on client, you should execute 'fdsl_client.py -d debug -m gateway' as root

**Comment by fdslight** [comment]
you can also see https://fdslight.github.io/fdslight/

**Comment by comk88** [comment]
Thank you for your replay, I've succeed deploy fds once,this the second time I deploy it ,get it, I will try it
best wishes
