### ISSUE TITLE
Can fdslight limit stream when it work in server--client:gateway mode?

### ISSUE THREAD

**Issue by comk88** [fdslight/fdslight#5]
Can fdslight limit stream when it work in server--client:gateway mode?

I have a probem people use together in client:gateway mode,if one download something rapdly, others maybe cant access the http website,so is there any method to limit the total speed of everyone

**Comment by fdslight** [comment]
it has simple QOS(allocate traffic average),maybe it is not good simple QOS,let me see...

**Comment by fdslight** [comment]
the VPN data over tcp or udp, at tcp,it cannot limit speed if you downloading ,i suggest you use udp as tunnel protocol, maybe it is ok.

**Comment by comk88** [comment]
it's over udp, how can I set it, 3Q very match,

**Comment by fdslight** [comment]
edit fn_client.ini file, modify tunnel_type = udp  on client.

**Comment by comk88** [comment]
Er, now it's udp , is the QOS need to be opened by myself or it is opened default?

**Comment by fdslight** [comment]
it is default.

**Comment by comk88** [comment]
ok, thank you very much  ,may you success
