### ISSUE TITLE
请问是否有伪造TCP用户IP的功能, 是如何实现的呢?

### ISSUE THREAD

**Issue by majoson-chen** [fdslight/fdslight#9]
假设代理服务器 (IP 100.100.100.100 ) 向某网站发送了一个 TCP 请求, 是否有方法将这个 TCP 请求的 IP 伪造成用户的 IP (123.123.123.123), 使得网站服务器获取到的TCP套接字中的请求 IP 是 123.123.123.123 ?
这个问题困扰很久, 感激不尽

**Comment by fdslight** [comment]
那是不可能的，只能是代理服务器的IP地址。

**Comment by fdslight** [comment]
昨天讲的是这个软件实现不了你需要的功能。因为在服务端会做nat。实现这种功能两种办法，一是服务器厂家提供多个ip地址，你在本地配置一个，服务器不要配置这个地址，需要代理服务器访问时终端路由指向改一下就好了，当然如果是二层vpn更简单。还有一种是你的代理服务器作为bgp路由器，和服务器厂家做了bgp互联。

**Comment by majoson-chen** [comment]
那假设我有n个用户，是否意味着我需要n个独立ip地址，我的想法是能不能通过类似于修改tcp或者ip报文的方式伪装ip地址。

**Comment by fdslight** [comment]
那不就是代理吗，代理服务器就是代理你的请求，显示的IP地址就是代理服务器地址。而且你随便设置地址是通不了的，互联网路由到不了你这里，而且有些设备为了安全考虑都过不去。
